apiVersion: batch/v1
kind: CronJob
metadata:
  name: usc-sign-in-bot
spec:
  schedule: "0 12 * * *" # This will run at midday every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: usc-sign-in-bot
            image: michielvandenengel/usc-bot:latest
            command: ["python", "-m", "usc_sign_in_bot", "job"]
            env:
            - name: UVA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uva-login
                  key: username
            - name: UVA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uva-login
                  key: password
            - name: BOTTOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bottoken
                  key: BOTTOKEN
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgressysuser
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgressysuser
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgressysuser
                  key: password
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          restartPolicy: OnFailure
