apiVersion: apps/v1
kind: Deployment
metadata:
  name: usc-telegram-deployment
  namespace: usc
spec:
  replicas: 1  # Number of pods
  selector:
    matchLabels:
      app: usc-telegram-deployment
  template:
    metadata:
      labels:
        app: usc-telegram-deployment
    spec:
      containers:
        - name: usc-telegram-container
          image: michielvandenengel/usc-bot:latest
          command: ["python", "usc_sign_in_bot/telegram_bot.py"]
          env:
          - name: ENCRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: encryptionkey
                key: ENCRYPT_KEY
          - name: BOTTOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-bottoken
                key: BOTTOKEN
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgressysuser
                key: database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgressysuser
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgressysuser
                key: password